version: "3.8"
services:
  posts_db:
    container_name: posts_db
    user: root
    image: postgres:13.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
#        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./data:/var/lib/postgresql/data

  pg_admin:
    container_name: pg_admin
    user: root
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin


  posts:
    container_name: posts
    user: root
    build: .
    restart: always
    ports:
      - "80:8001"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - posts_db
    links:
      - posts_db
    volumes:
      - .:/app

volumes:
    data:
    posts:
    pgadmin:

